name: Party Event Plugin CI tests

on:
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint PHP code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=WordPress .

  test:
    name: Run PHP Unit tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_USER: incognito
          MYSQL_PASSWORD: "Gox56s0|k8~A"
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
      - name: Install WordPress test library
        run: bash bin/install-wp-tests.sh wordpress_test incognito Gox56$0|k8~A 127.0.0.1:3306 latest
      - name: Run tests
        run: vendor/bin/phpunit