name: Party Event Plugin CI tests

on:
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint PHP code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=WordPress .
        
  test:
    name: Run PHP Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
      - name: Install WordPress test library
        run: bash bin/install-wp-tests.sh wordpress_test root '' localhost latest
      - name: Run tests
        run: vendor/bin/phpunit
